select * from departments;
select * from employees;

insert into employees (EMP_ID, EMP_NAME, EMAIL, SALARY, DEPT_ID) values 
(104, 'Goutham Raj', 'goutham@gmail.com', 78000, 2),
(105, 'Raj Kumar', 'raj@gmail.com', 82000, 2),
(106, 'Nitin', 'nitin@gmail.com', 86000, 1),
(107, 'Varma', 'varma@gmail.com', 88000, 3);


-- Step 1: Create a mapping table that links Snowflake usernames to DEPT_ID
CREATE TABLE IF NOT EXISTS STAR_INSURANCE.INSURANCE_SCHEMA.USER_DEPT_MAPPING (
    USERNAME VARCHAR(100) NOT NULL,
    DEPT_ID NUMBER(38,0) NOT NULL
);

-- Step 2: Insert sample mappings (adjust usernames/dept_ids as needed)
INSERT INTO STAR_INSURANCE.INSURANCE_SCHEMA.USER_DEPT_MAPPING (USERNAME, DEPT_ID)
VALUES
    ('SRAVI', 1),
    ('TEST_USE1', 2);

-- Step 3: Create the row access policy
CREATE OR REPLACE ROW ACCESS POLICY STAR_INSURANCE.INSURANCE_SCHEMA.RAP_DEPT_ACCESS
AS (dept_id NUMBER) RETURNS BOOLEAN ->
    IS_ROLE_IN_SESSION('ACCOUNTADMIN')
    OR EXISTS (
        SELECT 1
        FROM STAR_INSURANCE.INSURANCE_SCHEMA.USER_DEPT_MAPPING m
        WHERE m.USERNAME = CURRENT_USER()
          AND m.DEPT_ID = dept_id
    );

-- Step 4: Apply the row access policy to EMPLOYEES table
ALTER TABLE STAR_INSURANCE.INSURANCE_SCHEMA.EMPLOYEES
    ADD ROW ACCESS POLICY STAR_INSURANCE.INSURANCE_SCHEMA.RAP_DEPT_ACCESS ON (DEPT_ID);

-- Step 5: Apply the row access policy to DEPARTMENTS table
ALTER TABLE STAR_INSURANCE.INSURANCE_SCHEMA.DEPARTMENTS
    ADD ROW ACCESS POLICY STAR_INSURANCE.INSURANCE_SCHEMA.RAP_DEPT_ACCESS ON (DEPT_ID);

-- Step 6: Create a masking policy on EMAIL column
CREATE OR REPLACE MASKING POLICY STAR_INSURANCE.INSURANCE_SCHEMA.MASK_EMAIL
AS (val VARCHAR) RETURNS VARCHAR ->
    CASE
        WHEN IS_ROLE_IN_SESSION('ACCOUNTADMIN') THEN val
        ELSE CONCAT('***@', SPLIT_PART(val, '@', 2))
    END;

-- Step 7: Apply the masking policy to EMPLOYEES.EMAIL
ALTER TABLE STAR_INSURANCE.INSURANCE_SCHEMA.EMPLOYEES
    MODIFY COLUMN EMAIL SET MASKING POLICY STAR_INSURANCE.INSURANCE_SCHEMA.MASK_EMAIL;

-- Drop masking policy from EMPLOYEES table
ALTER TABLE STAR_INSURANCE.INSURANCE_SCHEMA.EMPLOYEES
    MODIFY COLUMN EMAIL UNSET MASKING POLICY;

DROP MASKING POLICY STAR_INSURANCE.INSURANCE_SCHEMA.MASK_EMAIL;


-- Step 8: Create a masking policy on SALARY column
CREATE OR REPLACE MASKING POLICY STAR_INSURANCE.INSURANCE_SCHEMA.MASK_SALARY
AS (val NUMBER) RETURNS NUMBER ->
    CASE
        WHEN IS_ROLE_IN_SESSION('ACCOUNTADMIN') THEN val
        ELSE NULL
    END;

-- Step 7: Apply the masking policy to EMPLOYEES.EMAIL
ALTER TABLE STAR_INSURANCE.INSURANCE_SCHEMA.EMPLOYEES
    MODIFY COLUMN SALARY SET MASKING POLICY STAR_INSURANCE.INSURANCE_SCHEMA.MASK_SALARY;

-- Drop masking policy from EMPLOYEES table
ALTER TABLE STAR_INSURANCE.INSURANCE_SCHEMA.EMPLOYEES
    MODIFY COLUMN SALARY UNSET MASKING POLICY;

DROP MASKING POLICY STAR_INSURANCE.INSURANCE_SCHEMA.MASK_SALARY;
