-- Create new warehouse

CREATE WAREHOUSE IF NOT EXISTS BANKING_TEST_WH
  WITH
  WAREHOUSE_SIZE = 'XSMALL'
  WAREHOUSE_TYPE = 'STANDARD'
  GENERATION = '2'
  MAX_CLUSTER_COUNT = 3
  MIN_CLUSTER_COUNT = 1
  SCALING_POLICY = 'STANDARD'
  AUTO_SUSPEND = 300
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE
  ENABLE_QUERY_ACCELERATION = TRUE
  QUERY_ACCELERATION_MAX_SCALE_FACTOR = 8
  COMMENT = 'Warehouse for banking sector testing workloads';

show warehouses;

show warehouses like 'BANKING_TEST_WH%';

-- Create a new Role

CREATE ROLE IF NOT EXISTS BANKING_TEST_ROLE
  COMMENT = 'Role for banking sector testing activities';

show roles;

-- Grant the Warehouse to Role that was created

GRANT USAGE ON WAREHOUSE BANKING_TEST_WH TO ROLE BANKING_TEST_ROLE;

-- Grant usage on Database

GRANT USAGE ON DATABASE STAR_INSURANCE TO ROLE BANKING_TEST_ROLE;

-- Grant usage on Schema

GRANT USAGE ON SCHEMA STAR_INSURANCE.INSURANCE_SCHEMA TO ROLE BANKING_TEST_ROLE;

-- Create a new user

CREATE USER IF NOT EXISTS TEST_USE1
  PASSWORD = 'ChangeMe123!'
  DEFAULT_ROLE = PUBLIC
  DEFAULT_WAREHOUSE = BANKING_TEST_WH
  MUST_CHANGE_PASSWORD = TRUE
  LOGIN_NAME= "TEST_USER1"
  DISPLAY_NAME = "USER1"
  COMMENT = 'Test user for banking sector';

-- Grant a Role to the User

GRANT ROLE BANKING_TEST_ROLE TO USER TEST_USE1;

-- Grant all table that are in schma access to a role

GRANT SELECT ON ALL TABLES IN SCHEMA STAR_INSURANCE.INSURANCE_SCHEMA TO ROLE BANKING_TEST_ROLE;

-- Grant access on future tables that are add later in a schema

GRANT SELECT ON FUTURE TABLES IN SCHEMA STAR_INSURANCE.INSURANCE_SCHEMA TO ROLE BANKING_TEST_ROLE;

-- Grant single table to a Role

GRANT SELECT ON TABLE STAR_INSURANCE.INSURANCE_SCHEMA.dimcustomer TO ROLE BANKING_TEST_ROLE;
GRANT SELECT ON TABLE testdb.test_schema.auction_data TO ROLE BANKING_TEST_ROLE;
GRANT SELECT ON TABLE testdb.test_schema.employees TO ROLE BANKING_TEST_ROLE;

select * from testdb.test_schema.employees;
